### ISSUE TITLE
Out of Memory-error

### ISSUE THREAD

**Issue by MSavels** [EasyinnovaSL/DPFManager#402] opened 2017-04-20 08:42 UTC
While analyzing certain datasets, the program starts to slow down considerably and in the end throws an Out-of-Memory-error. The program continues to run, but at an excruciatingly slow pace, throwing the same error regularly.

- Version: DPF Manager v3.2 with built-in Java Virtual Machine. Called from script as dpf-manager-console.exe
- System: Windows 8.1 Pro x64 | 8,00 GB RAM | Intel Core i7-4770@3,40 GHz
- Java version of the OS (not sure if this is relevant): 1.8.0_111 (with -Xmx1G)

The error is consistently thrown while analyzing a dataset of 146 GB, consisting of 7871 tiffs and some 2000 other file formats, but has popped up on smaller datasets as wel (lowest: 33,4 GB, containing 1117 tiffs). I wonder if this is caused by the maximum heap size of the built-in Java (set at -Xmx512M) and if it is possible for a user to change this.

Thanks in advance

**Comment by victormunoz** [comment] 2017-04-20 09:49
Thank you for reporting this issue, we will try to reproduce it.
Can you tell us which ISOs are you validating? Have you defined any policy, or fix? Which report formats are you generating?
The non-TIFF files are ignored, unless you have configured external conformance checkers. Have you?

**Comment by MSavels** [comment] 2017-04-20 12:40
It is validating against all ISO's. I have used only the default configuration, so no user-defined policies or fixes. Report format is json. I haven't used external conformance checkers for the non-TIFF-files.

The  command line code is `"C:\Program Files\DPF Manager\dpf-manager-console.exe" check --recursive --silence --format json path\to\dataset`

**Comment by victormunoz** [comment] 2017-04-24 10:15
Hello. Up to now I have been unable to reproduce this issue...
I've made several runs with datasets of hundreds of Gb and thousands of tiffs without any problem at all.

I think the problem is not related with the java heap size, because I've tried reducing it down to 128Mb and still no errors appear. Moreover, if this was the problem, the error description should explicitly say "Java heap space" out of memory exception.

Therefore I guess the problem may be originated by some characteristics of the Tiff files itself.
Can you look at the log and identify wich file/s produce this out-of-memory error? Are the same files always which generate the error? What if you run these problematic files separately? does the error still occurs?

**Comment by MSavels** [comment] 2017-04-24 12:38
As far as I can tell, the problem is'n tied to a specific file (the error has popped up in different datasets with different files). The .log-file doesn't give any interesting information in that respect either, but the file dpfmanager.h2.trace.db does mention some exceptions. Since I'm not familiar with Java, I don't know what to make of them. I'll put the last three entries in a text file and attach them to this post. 
[dpfmanager_h2_trace_db_excerpt.txt](https://github.com/EasyinnovaSL/DPFManager/files/951711/dpfmanager_h2_trace_db_excerpt.txt)

**Comment by victormunoz** [comment] 2017-04-25 07:43
Thanks for the log file. The error seems to be produced in the internal database (it is used to update the statistics of the current running job). It is not an essential module, and the program should can continue its execution "normally".

However for the next release we will make a minor change in the database, which may possibly fix this error (can't assure this, because I have not been able to reproduce the error, yet).

Does the error also occur with the GUI?

**Comment by MSavels** [comment] 2017-04-25 07:55
I haven't checked this with the GUI, but I will try to do so in the course of this week. I was also thinking of experimenting with the Lite version.

**Comment by victormunoz** [comment] 2017-04-28 12:36
The new version of the DPF Manager has been released!
Please check if the error still occurs with the new version.
I am going to close this issue, but reopen it if the problem persists.

**Closed by victormunoz** 2017-04-28 12:36 UTC
Labels: unable to reproduce

**Comment by MSavels** [comment] 2017-05-11 06:57
I installed the new version (with embedded Java) and ran some test. No more Out-of-Memory-errors were thrown. I then decided to push the software a little. I ran it on a dataset with 124,960 TIFF's (size: 2445.75 GB). After about six and a half hours of near-100% processor load, the job finished succesfully. So for me, the problem is solved. Thanks for the help.

**Comment by victormunoz** [comment] 2017-05-11 07:14
Great! Thank you!
