### ISSUE TITLE
Weird characters in report in DPF Manager

### ISSUE THREAD

**Issue by nvanderperren** [EasyinnovaSL/DPFManager#374] opened 2017-02-02 15:28 UTC
I've got weird characters in my reports in DPF Manager. When I open the HTML-reports in my browser (Firefox), the weird chars are gone.

operating system is OS X El Capitan V. 10.11.16

<img width="956" alt="schermafbeelding 2017-01-11 om 09 57 36" src="https://cloud.githubusercontent.com/assets/17183054/22555617/8c796d24-e964-11e6-82ea-ed45889ff777.png">
<img width="978" alt="schermafbeelding 2017-01-11 om 09 57 45" src="https://cloud.githubusercontent.com/assets/17183054/22555618/8c79f23a-e964-11e6-99d9-bfd512ceaae9.png">
<img width="1280" alt="schermafbeelding 2017-02-02 om 16 27 21" src="https://cloud.githubusercontent.com/assets/17183054/22555629/96521b7a-e964-11e6-93fa-d7772f5e8464.png">
<img width="1280" alt="schermafbeelding 2017-02-02 om 16 27 33" src="https://cloud.githubusercontent.com/assets/17183054/22555630/96567e86-e964-11e6-8848-9c87fe409877.png">

**Comment by victormunoz** [comment] 2017-02-03 07:16
Hello,
Can you please send us the TIFF file that produces this invalid report, or the report itself, so that we can reproduce it?
Thank you!

**Comment by nvanderperren** [comment] 2017-02-03 08:31
the file is too big to upload. is there an e-mailadress that I can use to send to? I have this problem with all tiff files on our server; not with one or some in particular.

**Comment by victormunoz** [comment] 2017-02-03 08:41
You can use [WeTransfer](https://wetransfer.com/) to send huge files.
My email address is victormunoz@easyinnova.com

**Comment by victormunoz** [comment] 2017-02-03 11:06
Ok. I have been able to reproduce this issue.
The problem is related to a font included in the report that for some reason the web viewer of JavaFX does not recognize. But it seems to happen only with Mac OS systems.
We will look for a fix for this.
Thank you very much for reporting!

**Comment by victormunoz** [comment] 2017-02-03 12:18
I have created a hotfix that solves this.
You can download it only at our website (not in the open source portal): http://dpfmanager.org/index.html#download

**Comment by nvanderperren** [comment] 2017-02-03 12:34
ok, thx!

2017-02-03 13:18 GMT+01:00 Victor Muñoz <notifications@github.com>:

**Closed** 2017-02-03 13:59 UTC
Labels: bug
